### ISSUE TITLE
Problems with Particle System

### ISSUE THREAD

**Issue by Flchsh** [Team-Innis/UtH-Engine#28]
Setting and changing particle color is not working or keeps setting back to neutral values. Also setting particle speed in ParticleTemplate doesn't seem to do anything.

**Comment by DrJonki** [comment]
By default the particle system only updates the internal buffers when one or more particles have been removed since the last frame. To force an update, in the affector `Update` function you'll need to call GetSystem()->RaiseUpdateFlag(). In the current release this function is not working correctly, but has been fixed in the development branch.

At this time the speed you pass into the template isn't used anywhere by default. Using the values, you'll need to calculate your own direction vector and assign it to the particles inside the affector's init function.
